# Generated by Django 5.0.7 on 2024-10-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eamil_2',
            new_name='email_2',
        ),
    ]
