# Generated by Django 5.0.7 on 2024-10-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_rename_eamil_2_user_email_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_2',
            field=models.EmailField(max_length=254),
        ),
    ]
